### ISSUE TITLE
Plugin Not Working With NinjaForms

### ISSUE THREAD

**Issue by AshutoshSwain** [rapidwebltd/permissions-editor-ninja-forms-plugin#1]
Plugin Is Not Working With NinjaForms... It's Showing Error...

**Comment by AshutoshSwain** [comment]
$penfCapability) { if($penfCapabilityKey == "penf_view_menu"){continue;} echo ""; } ?> roles as $roleKey => $role) { ?> ".$role['name'].""; foreach(penf_get_caps() as $penfCapabilityKey => $penfCapability) { if($penfCapabilityKey == "penf_view_menu"){continue;} ?>

**Comment by AshutoshSwain** [comment]
Version 3.2.4

**Comment by kirsty-gasston** [comment]
Could you please provide us with some more information as we are unable to replicate this at all in any testing.

What version of WordPress are you using?

And what steps did you take prior to seeing this error?

**Comment by kirsty-gasston** [comment]
We've made an update to the plugin to change from PHP shorthand tags as we suspect that perhaps you might have short tags disabled?

Would you be able to pull and try again please?

**Comment by AshutoshSwain** [comment]
Error While Installing... Kindly Help Ma'am...

**Comment by kirsty-gasston** [comment]
Can you please provide details of the error that you have received?

**Comment by kirsty-gasston** [comment]
We believe that we may have found and resolved the problem - you should be able to install the latest version of the plugin which fixes this.

**Comment by AshutoshSwain** [comment]
Thank You Ma'am... It's Working Now In The Latest Version Of NinjaForms Plugin But Not In Version 3.16 Of NinjaForms...

**Comment by kirsty-gasston** [comment]
We have test retested with version 3.1.6 and can see no issues - can you please provide more information?

**Comment by AshutoshSwain** [comment]
Yeah... It's Working Fine Now...
