### ISSUE TITLE
What's The Use Of It!!!

### ISSUE THREAD

**Issue by AshutoshSwain** [rapidwebltd/permissions-editor-ninja-forms-plugin#2]
One Thing Ma'am... What's The Use Of It!!! It's Only For Display Of Alternate Menu Items Of NinjaForms Like "Manage | Submissions | Import / Export | Settings"...

What A Editor / Author / Contributor / Subscriber Will Do With "Manage | Submissions | Import / Export | Settings"???

It Would Have More Useful If It Would Have Different Option For Different User Role In Submission Itself...
Like...
Editor Can Delete / Modify Any Submission...
Author Can Delete / Modify It's Own Submission...
Contributor Can Modify It's Own Submission But Can Not Delete The Submission...
Subscriber Can Only View The Submission...

**Comment by kirsty-gasston** [comment]
By default, all aspects of Ninja Forms are available only to users of role 'Administrator' - our plugin enables you to give other user roles access to some or all elements of Ninja Forms. This can be useful, for example, in enabling the 'Editor' user to add new forms or edit existing ones, and to enable other user roles to view the form submissions.

The options that you suggest would be great, but are unfortunately not possible within the limitations of Ninja Forms.
